services:
  - type: web
    name: buffett-analyzer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0 