services:
  - type: web
    name: buffett-analyzer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0 